const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const inlineScripts = Array.from(html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi), match => match[1]).filter(source => source.trim());
assert.ok(inlineScripts.length >= 2, 'expected version guard and application scripts');
inlineScripts.forEach((source, index) => new vm.Script(source, { filename: `index.inline.${index + 1}.js` }));

assert.match(html, /data-claim-bill-form/);
assert.match(html, /name="claimQty"/);
assert.match(html, /data-action="assign-stock-vendor"/);
assert.match(html, /data-action="claim-bill-print"/);
assert.match(html, /data-action="claim-bill-edit"/);
assert.match(html, /data-action="claim-bill-cancel"/);
assert.match(html, /data-action="claim-bill-notify"/);
assert.match(html, /executeBillPrintPreview/);
assert.match(html, /PENDING_CLAIM_MUTATIONS_KEY/, 'claim mutations must retain their ID across ambiguous client failures');
assert.match(html, /sessionStorage\.setItem\(PENDING_CLAIM_MUTATIONS_KEY/, 'pending mutation recovery must survive a page reload in the same tab');
assert.match(html, /postData\.lastFailureAmbiguous/, 'client must distinguish definitive server rejection from ambiguous transport failure');
assert.match(html, /result\.reason === 'maybe_committed'/, 'committed-business/ledger ambiguity must retain the mutation ID');
assert.match(html, /token: \(appUser && appUser\.token\)/, 'mutations must include the verified SSO token');
assert.match(html, /addReturnWithClaim/, 'damaged returns must persist Return Record and Damage Goods Report through one backend mutation');
assert.match(html, /postClaimMutation\('return-with-claim'/, 'damaged return intake must reuse its mutation identity after an ambiguous response');
assert.match(html, /btnSubmitDrafts\.disabled.*btnSubmitDrafts\.disabled\s*=\s*true.*finally.*btnSubmitDrafts\.disabled\s*=\s*false/s, 'damaged-goods draft submission must be single-flight in the UI');
assert.match(html, /saved\.payload.*requestPayload/s, 'ambiguous retries must resend the original timestamped return payload');
assert.match(html, /id:qcResult === 'C' \? '' : 'RET-'\+Date\.now\(\)/, 'damaged return IDs must derive from the retained mutation ID');
assert.doesNotMatch(html, /qcOk\s*=\s*await postData\(\{ action:'updateReturnQC'/, 'damaged return intake must not depend on a second client mutation');
assert.match(html, /hasPermissionContract.*appUser\.perms/s, 'frontend must distinguish current permission contracts from legacy tokens');
assert.match(html, /function buildVerifiedSessionUser\(/, 'verified SSO users must be normalized without inventing a permission contract');
assert.doesNotMatch(html, /perms:\s*result\.user\.perms\s*\|\|\s*\{\}/, 'legacy verified users without perms must not be converted into authoritative-empty permissions');
assert.doesNotMatch(html, /if \(retPerms\.length === 0\) return true/, 'authoritative empty permissions must not grant every action');
assert.doesNotMatch(html, /roles\.includes\('ADMIN'\) \|\| roles\.includes\('SUPERVISOR'\)\) return true/, 'current ADMIN and SUPERVISOR tokens must not bypass authoritative empty permissions');
assert.doesNotMatch(html, /if \(isAdmin\) return;/, 'authoritative ADMIN tokens must not bypass tab-level permissions');
assert.match(html, /const STORAGE_KEY = "akra_returnitem_session"/, 'Returnitem must keep its token in an app-scoped session key');
assert.doesNotMatch(html, /const STORAGE_KEY = "akra_sso_user_data"/, 'Returnitem must not couple its token lifecycle to KPITracker shared profile storage');
assert.match(html, /function activeCacheKey\(\).*appUser.*id.*returnitemPermissionsForUser/s, 'protected active cache must be scoped to verified identity and authorization');
assert.match(html, /cacheSafeActiveData\(getCache\(activeCacheKey\(\), RETURN_CACHE_TTL\)\)/, 'cached active data must be stripped before it can render');
assert.match(html, /setCache\(activeCacheKey\(\), cacheSafeActiveData\(res\.data\)\)/, 'protected claim data must not be written to the active cache');
assert.doesNotMatch(html, /setCache\(activeCacheKey\(\), res\.data\)/, 'raw protected claim payloads must never enter the active cache');
assert.match(html, /function handleClaimBillAuthError\(error, allowOrdinaryData = false\)/, 'frontend must distinguish expected claim denial from terminal bootstrap auth failures');
assert.match(html, /claimBillAuthError.*handleClaimBillAuthError\(res\.data\.claimBillAuthError, true\)/s, 'default bootstrap must preserve ordinary data when only claim-bill access is denied');
assert.match(html, /error\.reason === 'permission_denied'.*return !allowOrdinaryData/s, 'permission-denied claim reads must only stop claim-specific requests');
assert.match(html, /includeProducts=0&token=/, 'claim bill reads must include the verified SSO token');
assert.match(html, /window\.executeBillPrintPreview\s*=\s*async function/, 'bill print must wait for authoritative server state');
assert.match(html, /action=getClaimBillForPrint.*billId=.*token=/s, 'bill print must use an authenticated bill-by-ID read');
assert.match(html, /res\.data\.claimBill.*res\.data\.claimBillLines/s, 'bill print must render the authoritative header and committed lines');
assert.match(html, /function formatClaimUnitTotals\(/, 'mixed claim units must be summarized per unit');
assert.match(html, /function roundClaimQty\(/, 'claim quantities must share a six-decimal-safe rounding helper');
assert.doesNotMatch(html, /const total = lines\.reduce\(\(sum, line\) => sum \+ Number\(line\.qty \|\| 0\), 0\)/, 'bill cards must not add unlike units into one number');
assert.doesNotMatch(html, /const totalQty = items\.reduce\(/, 'legacy tracking cards must not add unlike units into one number');
assert.match(html, /id="manage_ready_bills"/, 'MANAGE_CLM creators need an initial print surface');
assert.match(html, /!can\('MANAGE_CLM'\) && !can\('TRACK_CLM'\)/, 'print action must allow either manage or tracking permission');
assert.doesNotMatch(html, /'track-notify':'TRACK_CLM'/, 'legacy in-flight tracking actions must remain usable by MANAGE_CLM users');
assert.doesNotMatch(html, /'print-track':'TRACK_CLM'/, 'legacy reprints must remain usable by MANAGE_CLM users');
assert.match(html, /\['claim-bill-print','print-track'\]/, 'new-bill and legacy reprints must accept the same manage-or-track authorization');
assert.match(html, /\['claim-bill-notify','claim-bill-resolve','claim-bill-receive','track-notify','track-resolve','track-receive-new'\]/, 'legacy and bill tracking actions must accept the same manage-or-track authorization');
assert.match(html, /data-action="claim-bill-print"[^>]*aria-label=/, 'repeated print buttons need bill-specific accessible names');
assert.match(html, /data-action="claim-bill-cancel"[^>]*aria-label=/, 'repeated cancel buttons need bill-specific accessible names');
assert.match(html, /id="claim-stock-search"/, 'damaged stock must be searchable');
assert.match(html, /id="claim-history-load-more"/, 'closed claim history must expose pagination');
assert.match(html, /function loadMoreClaimBillHistory\(/, 'frontend must retrieve older closed bills');
assert.match(html, /action=getClaimBillHistory/, 'history pagination must use the authenticated backend endpoint');
assert.match(html, /id="bill-resolution-amount"/, 'bill deduction resolution must capture the amount');
assert.match(html, /id="bill-resolution-reject-reason"/, 'unclaimable resolution must capture its reason explicitly');
assert.match(html, /claimAmount:result\.value\.claimAmount/, 'resolution mutations must send the validated amount');
assert.match(html, /วันหมดอายุ/, 'claim print must include expiry detail');
assert.match(html, /documentRef \|\| \('CLM-'/, 'new bill print must accept a durable document reference');
assert.match(html, /const waitList = \[\]/, 'legacy waiting rows must not also render as new bill tracking');

assert.match(html, /id="wh-select-all"/, 'warehouse intake must provide select all checkbox');
assert.match(html, /id="btn-wh-bulk-in"/, 'warehouse intake must provide bulk receive button');
assert.match(html, /function updateWhSelectCount\(/, 'frontend must manage selection count');
assert.match(html, /function toggleWhSelectAll\(/, 'frontend must support toggling all selections');
assert.match(html, /function executeWHReceive\(/, 'frontend must support single and bulk warehouse receive');
assert.match(html, /<option value="W1">W1 \(TRD\)<\/option>/, 'warehouse receive must offer W1 dropdown option');
assert.match(html, /<option value="W2" selected>W2 \(AKRA\)<\/option>/, 'warehouse receive must offer W2 dropdown option');
assert.match(html, /<option value="W3">W3<\/option>/, 'warehouse receive must offer W3 dropdown option');
assert.match(html, /<option value="W4">W4<\/option>/, 'warehouse receive must offer W4 dropdown option');
assert.match(html, /<option value="W5">W5<\/option>/, 'warehouse receive must offer W5 dropdown option');
assert.match(html, /id="sw-wh-user"/, 'warehouse receive must provide receiver input with autofilled default');

assert.match(html, /id="claim-stock-available"/, 'damaged stock must expose prominent available quantity element');
assert.match(html, /id="claim-stock-received"/, 'damaged stock must expose received quantity element');
assert.match(html, /<span>คงเหลือพร้อมเคลม:<\/span>/, 'header must highlight remaining available stock');

const currentVersion = html.match(/const CURRENT_VERSION = "([^"]+)"/);
const version = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'version.json'), 'utf8')).version;
assert.ok(currentVersion);
assert.strictEqual(currentVersion[1], version, 'CURRENT_VERSION and version.json must match');
assert.match(html, /const GAS_URL = 'https:\/\/script\.google\.com\/macros\/s\/AKfycbxpCu71JGbGcBDO_v3wrAs9eT3efh1aSQK4m7VhoOU5K5EO4GTGVWFNdPA-R6icQXA\/exec';/, 'frontend must use the verified backend GAS deployment');
assert.strictEqual(version, '20260819.02', 'damaged stock available prominence requires frontend version 20260819.02');

console.log('claim bill frontend static contract passed');
